### ISSUE TITLE
Twitter alternative

### ISSUE THREAD

**Issue by Snarkly** [rcmcintosh/twitter-clone#1]
You need to make your clone like the old Twitter in this picture and get it up and running for people to use. People are looking for a good Twitter alternative because Twitter has gone down hill. They censor everything now and shadowban people. I've done a little research and people seem to want features like Twitter removed. People want to use gifs for avatars and they want to be able to upload an image to use as their background just like in this example picture. I would even give it a name like Tweetter, it's close to Twitter and it would attract a lot of people to it. If you can create a good Twitter replace I will promote it. ![twitterclone](https://cloud.githubusercontent.com/assets/8492776/24215726/04d66260-0f10-11e7-8cc9-a2aa2d97473b.png)

**Comment by RealTrent** [comment]
+1, @Snarkly makes some good points here. @rmcintosh you should spin this off.

**Comment by rmcintosh** [comment]
@RealTrent while my interest in spinning this off is limited (as I'm unfamiliar with it) @rcmcintosh may feel differently... 😜

**Comment by Snarkly** [comment]
I also did a little research on twitter and took a screenshot of what people are saying about the features Twitter removed. On the left of this pic people are talking about the background and on the right about the gifs. This was only a few people I took a screenshot of, there were thousands more people but it would have took me weeks to screenshot everybody. I've seen many people talking about looking for an alternative because they want to leave Twitter but there's no good alternative. Please consider creating one and thanks for taking the time to read my comments. ![oldtwitter2](https://cloud.githubusercontent.com/assets/8492776/24466232/251f2e30-147e-11e7-95fc-840894d8a0af.png)
